### ISSUE TITLE
Valorant API not responding.

### ISSUE THREAD

**Issue by nimit2801** [nimit2801/fuzzy-bones#4]
The API which gave data to the bot for Valorant ranks has been giving _401 error in Heroku logs_.
Anyone who has experience with **APIs** and **DiscordJs** can easily solve this.

**Comment by Henrik-3** [comment]
A bit late Probably, but I had to take down the Endpoint because Tracker.gg asked me friendly to do it and I don't want to get any legal issues at this point.

**Comment by nimit2801** [comment]
Got it thanks @Henrik-3 for informing :D

**Comment by nimit2801** [comment]
Closing this issue for now, since there is no official API for valorant. Would reopen if the official API is available!
